FlashSpace/MainView.swift, FlashSpace/MainViewModel.swift, FlashSpace/Settings/FocusManagementView.swift, FlashSpace/Workspaces/Workspace.swift, FlashSpace/Workspaces/WorkspaceManager.swift, FlashSpace/Workspaces/WorkspaceRepository.swift, README.md
=> feat: select app to focus on workspace activation

FlashSpace.xcodeproj/project.pbxproj, FlashSpace/Settings/IntegrationsSettingsView.swift, FlashSpace/Settings/SettingsRepository.swift, FlashSpace/Settings/SettingsView.swift, FlashSpace/Utils/Integrations.swift, FlashSpace/Workspaces/WorkspaceManager.swift, README.md
=> feat: added SketchyBar integration

FlashSpace.xcodeproj/project.pbxproj, FlashSpace/Core/AppDependencies.swift, FlashSpace/Extensions/NotificationName.swift, FlashSpace/MainViewModel.swift, FlashSpace/Settings/FocusSettingsView.swift, FlashSpace/Settings/IntegrationsSettingsView.swift, FlashSpace/Settings/SettingsRepository.swift, FlashSpace/Settings/SettingsView.swift, FlashSpace/Settings/WorkspacesSettingsView.swift, FlashSpace/Workspaces/WorkspaceManager.swift, README.md
=> feat: added shortcuts to cycle through workspaces & unassign apps

FlashSpace/Extensions/NSRunningApplication.swift, FlashSpace/Focus/FocusedWindowTracker.swift, FlashSpace/Workspaces/WorkspaceManager.swift
=> feat: improved performance

FlashSpace/Extensions/URL.swift, FlashSpace/FlashSpaceApp.swift, FlashSpace/MainView.swift, FlashSpace/MainViewModel.swift
=> fix: not showing some apps when adding using "+" button

FlashSpace/Components/InputDialog.swift, FlashSpace/Core/AppDependencies.swift, FlashSpace/Extensions/NotificationName.swift, FlashSpace/Extensions/URL.swift, FlashSpace/HotKeys/HotKeysManager.swift, FlashSpace/MainView.swift, FlashSpace/MainViewModel.swift, FlashSpace/Settings/IntegrationsSettingsView.swift, FlashSpace/Settings/ProfilesSettingsView.swift, FlashSpace/Settings/ProfilesSettingsViewModel.swift, FlashSpace/Settings/SettingsRepository.swift, FlashSpace/Settings/SettingsView.swift, FlashSpace/Settings/WorkspacesSettingsView.swift, FlashSpace/Utils/Integrations.swift, FlashSpace/Utils/ProfilesRepository.swift, FlashSpace/Workspaces/Workspace.swift, FlashSpace/Workspaces/WorkspaceManager.swift, FlashSpace/Workspaces/WorkspaceRepository.swift
=> feat: added support for profiles

FlashSpace/Core/AppConstants.swift, FlashSpace/MainView.swift, FlashSpace/MainViewModel.swift, FlashSpace/Settings/SettingsView.swift, FlashSpace/Workspaces/WorkspaceManager.swift
=> feat: added option to remember last focused app per workspace

FlashSpace/Settings/SettingsRepository.swift, FlashSpace/Settings/WorkspacesSettingsView.swift, FlashSpace/Utils/FloatingToast.swift, FlashSpace/Workspaces/WorkspaceManager.swift
=> feat: added floating notifications

FlashSpace/Extensions/NSRunningApplication.swift, FlashSpace/Focus/FocusedWindowTracker.swift, FlashSpace/Workspaces/Workspace.swift, FlashSpace/Workspaces/WorkspaceManager.swift
=> fix: switch workspace shortcuts when external display is disconnected

FlashSpace/Extensions/NSRunningApplication.swift, FlashSpace/Settings/MenuBarSettingsView.swift, FlashSpace/Workspaces/WorkspaceManager.swift
=> fix: reduced blinking while activating workspace

FlashSpace/MainViewModel.swift, FlashSpace/Workspaces/WorkspaceManager.swift
=> fix: invalid detection of background apps when using hot keys

FlashSpace/Extensions/AXUIElement.swift, FlashSpace/Extensions/NSRunningApplication.swift, FlashSpace/Focus/FocusManager.swift, FlashSpace/Focus/RunningApp.swift, FlashSpace/Settings/FocusSettingsView.swift, FlashSpace/Settings/SettingsRepository.swift
=> feat(focus): hot keys to switch between workspace windows

FlashSpace/Settings/SettingsRepository.swift, FlashSpace/Settings/WorkspacesSettingsView.swift, FlashSpace/Workspaces/WorkspaceManager.swift
=> feat(workspaces): option to prevent workspace change on app assign

README.md
Thank you @humblehacker for becoming a sponsor! 🍻
=> docs: updated sponsors

FlashSpace/Extensions/TextField.swift, FlashSpace/Settings/IntegrationsSettingsView.swift, FlashSpace/Settings/MenuBarSettingsView.swift, FlashSpace/Settings/SettingsRepository.swift, FlashSpace/Utils/MenuBarTitle.swift
=> feat: added display aliases for menu bar title

README.md
=> fix: videos in README.md

FlashSpace/Extensions/NotificationName.swift, FlashSpace/FlashSpaceApp.swift, FlashSpace/Settings/MenuBarSettingsView.swift
=> fix: improved refreshing menu bar after changing settings

FlashSpace/App/AppDependencies.swift, FlashSpace/Extensions/CornerRadius.swift, FlashSpace/Extensions/NSView.swift, FlashSpace/Extensions/NotificationName.swift, FlashSpace/HotKeys/HotKeysManager.swift, FlashSpace/Settings/SettingsRepository.swift, FlashSpace/Settings/SettingsView.swift, FlashSpace/Settings/SpaceControlSettingsView.swift, FlashSpace/SpaceControl/SpaceControl.swift, FlashSpace/SpaceControl/SpaceControlView.swift, FlashSpace/SpaceControl/SpaceControlViewModel.swift, FlashSpace/SpaceControl/SpaceControlWindow.swift, FlashSpace/SpaceControl/WorkspaceScreenshotManager.swift, FlashSpace/Utils/FloatingToast.swift, FlashSpace/Utils/PermissionsManager.swift, FlashSpace/Workspaces/Models/Workspace.swift, FlashSpace/Workspaces/WorkspaceManager.swift
=> feat: added Space Control with workspaces preview

FlashSpace/Extensions/AXUIElement.swift, FlashSpace/Extensions/NSRunningApplication.swift, FlashSpace/Settings/SettingsRepository.swift, FlashSpace/Settings/WorkspacesSettingsView.swift, FlashSpace/Workspaces/Models/PipBrowser.swift, FlashSpace/Workspaces/WorkspaceManager.swift
=> feat: support for Picture-in-Picture

FlashSpace/Settings/SettingsRepository.swift, FlashSpace/Settings/WorkspacesSettingsView.swift, FlashSpace/Workspaces/WorkspaceHotKeys.swift, README.md
=> feat: added shortcut to assign focused app to the active workspace

FlashSpace/Extensions/Array.swift, FlashSpace/Extensions/NotificationName.swift, FlashSpace/SpaceControl/SpaceControlView.swift, FlashSpace/SpaceControl/SpaceControlViewModel.swift, FlashSpace/SpaceControl/SpaceControlWindow.swift
=> feat: added arrow navigation in Space Control

FlashSpace.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, FlashSpace/Features/Config/ConfigSerializer.swift, FlashSpace/Features/Config/Models/ConfigCoder.swift, FlashSpace/Features/Config/Models/ConfigFormat.swift, FlashSpace/Features/Config/Models/JSONCoding.swift, FlashSpace/Features/Config/Models/TOMLCoding.swift, FlashSpace/Features/Config/Models/YAMLCoding.swift, FlashSpace/Features/Profiles/ProfilesRepository.swift, FlashSpace/Features/Settings/Models/AppSettings.swift, FlashSpace/Features/Settings/SettingsRepository.swift, FlashSpace/Features/Settings/Views/Acknowledgements/AcknowledgementsSettingsView.swift, FlashSpace/Features/Settings/Views/Acknowledgements/Licenses.swift, FlashSpace/Features/Settings/Views/ConfigurationFile/ConfigurationFileSettingsView.swift, FlashSpace/Features/Settings/Views/SettingsView.swift, README.md, project.yml
=> feat: added support for YAML and TOML config formats

FlashSpace/Features/MenuBar/FlashSpaceMenuBar.swift
=> feat: added profiles menu to Menu Bar

FlashSpace/Features/CLI/CLI.swift, project.yml
=> fix(cli): prompting for sudo access when calling (un)install

FlashSpace/Features/MainScreen/AppCell.swift, FlashSpace/Features/MainScreen/MainView.swift, FlashSpace/Features/MainScreen/MainViewModel.swift, FlashSpace/Features/MainScreen/WorkspaceCell.swift, FlashSpace/Features/MainScreen/WorkspaceConfigurationView.swift, FlashSpace/Features/Workspaces/Models/MacAppWithWorkspace.swift, FlashSpace/Features/Workspaces/WorkspaceManager.swift, FlashSpace/Features/Workspaces/WorkspaceRepository.swift, README.md, project.yml
=> feat: added drag & drop for workspaces + multiselect on both lists

FlashSpace/Features/CLI/Commands/WorkspaceCommands.swift, FlashSpace/Features/CLI/Models/CommandRequest.swift, FlashSpace/Features/CLI/Models/UpdateWorkspaceRequest.swift, FlashSpaceCLI/Sources/FlashSpaceCLI.swift, FlashSpaceCLI/Sources/Models/CommandRequest.swift, FlashSpaceCLI/Sources/Subcommands/Workspace/UpdateWorkspaceCommand.swift, project.yml
=> feat(cli): added `update-workspace` subcommand

FlashSpace/Features/CLI/Commands/WorkspaceCommands.swift, FlashSpace/Features/CLI/Models/UpdateWorkspaceRequest.swift, FlashSpaceCLI/Sources/Subcommands/Workspace/UpdateWorkspaceCommand.swift
=> fix(cli): fixed `active-display` option of `update-workspace` commmand

FlashSpace/Features/Settings/SpaceControl/SpaceControlSettings.swift, FlashSpace/Features/Settings/SpaceControl/SpaceControlSettingsView.swift, FlashSpace/Features/Settings/_Models/AppSettings.swift, FlashSpace/Features/SpaceControl/Views/SpaceControlViewModel.swift, project.yml
=> feat(space-control): added config option to limit number of columns

FlashSpace/Accessibility/AXUIElement+Properties.swift, FlashSpace/Accessibility/NSRunningApplication+Properties.swift, FlashSpace/Features/FocusManager/FocusManager.swift, project.yml
=> fix(focus-manager): incorrect behavior when the app is minimized

FlashSpace/Features/Settings/FloatingApps/FloatingAppsSettings.swift, FlashSpace/Features/Settings/FloatingApps/FloatingAppsSettingsView.swift, FlashSpace/Features/Settings/SpaceControl/SpaceControlSettingsView.swift, FlashSpace/Features/Settings/Workspaces/WorkspaceSettings.swift, FlashSpace/Features/Settings/Workspaces/WorkspacesSettingsView.swift, FlashSpace/Features/Settings/_Models/AppSettings.swift, FlashSpace/Features/SpaceControl/SpaceControl.swift, FlashSpace/Features/Workspaces/WorkspaceHotKeys.swift, project.yml
=> feat: added hotkeys to toggle assignment, floating, and SpaceControl

FlashSpace/Features/HotKeys/HotKeysManager.swift, FlashSpace/Features/Settings/General/GeneralSettingsView.swift
=> feat(hotkeys): added hotkey to toggle FlashSpace app visibility

FlashSpace/Features/HotKeys/HotKeysManager.swift, FlashSpace/Features/HotKeys/Models/KeyCodesMap.swift
=> fix(hotkeys): detection of keyboard layout change

FlashSpace/Accessibility/AXUIElement+Actions.swift, FlashSpace/Accessibility/AXUIElement+Properties.swift, FlashSpace/Accessibility/NSRunningApplication+Actions.swift, FlashSpace/Accessibility/NSRunningApplication+Properties.swift, FlashSpace/Extensions/CGRect.swift, FlashSpace/Extensions/NSScreen.swift, FlashSpace/Features/FocusManager/FocusManager.swift, FlashSpace/Features/SpaceControl/SpaceControl.swift, FlashSpace/UI/Toast.swift, project.yml
=> fix(workspaces): hiding apps based on window position

FlashSpace/Accessibility/NSRunningApplication+Actions.swift, FlashSpace/Extensions/NSScreen.swift, FlashSpace/Extensions/String.swift, FlashSpace/Features/PictureInPicture/PictureInPictureManager.swift, FlashSpace/Features/Settings/Workspaces/WorkspaceSettings.swift, FlashSpace/Features/Settings/Workspaces/WorkspacesSettingsView.swift, FlashSpace/Features/Settings/_Models/AppSettings.swift, FlashSpace/Features/Workspaces/Models/Workspace.swift, FlashSpace/Features/Workspaces/WorkspaceHotKeys.swift, project.yml
See: Settings -> Workspaces
Resolves #207
=> feat(workspaces): added "alternative displays" setting

FlashSpace/Accessibility/NSRunningApplication+Properties.swift, project.yml
=> fix(workspaces): performance when python with pygame module is running

FlashSpace/Accessibility/AXUIElement+CoreGraphics.swift, FlashSpace/Features/FocusManager/FocusManager.swift, FlashSpace/Features/Settings/FocusManager/FocusManagerSettings.swift, FlashSpace/Features/Settings/FocusManager/FocusSettingsView.swift, FlashSpace/Features/Settings/_Models/AppSettings.swift, project.yml
Resolves #214
See: Settings -> Focus Manager -> Experimental section
=> feat(focus-manager): added experimental setting to focus frontmost window

FlashSpace/App/AppDependencies.swift, FlashSpace/Features/Gestures/SwipeManager.swift, FlashSpace/Features/Settings/Gestures/GesturesSettings.swift, FlashSpace/Features/Settings/Gestures/GesturesSettingsView.swift, FlashSpace/Features/Settings/SettingsRepository.swift, FlashSpace/Features/Settings/SettingsView.swift, FlashSpace/Features/Settings/_Models/AppSettings.swift, README.md, project.yml
=> feat(gestures): added support for 3-fingers swipe to switch workspaces

FlashSpace/Features/Gestures/SwipeManager.swift, FlashSpace/Features/Settings/FocusManager/FocusSettingsView.swift, FlashSpace/Features/Settings/Gestures/GesturesSettings.swift, FlashSpace/Features/Settings/Gestures/GesturesSettingsView.swift, project.yml
Fixes #226
Resolved several issues with the following changes:
- Gesture is now recognized even without releasing touch
- 3 finger swipe works even if the palm is resting on the trackpad
- All fingers must contribute to the gesture in at least 20% each
- Gesture times out after 0.8s after the last event
=> feat(gestures): improved gesture detection

FlashSpaceCLI/Sources/Subcommands/List/ListRunningAppsCommand.swift
Example: `flashspace list-running-apps --with-bundle-id`
=> feat(cli): added `with-bundle-id` flag for `list-running-apps` command

FlashSpace/Features/Gestures/SwipeManager.swift, FlashSpace/Features/Settings/Gestures/GestureAction.swift, FlashSpace/Features/Settings/Gestures/GesturesSettings.swift, FlashSpace/Features/Settings/Gestures/GesturesSettingsView.swift, FlashSpace/Features/Settings/_Models/AppSettings.swift, project.yml
Breaking Changes: changed config options for gestures
=> feat(gestures)!: fully configurable gestures + added vertical swipes

.github/workflows/pr.yml, FlashSpace/Features/Integrations/Integrations.swift, project.yml
=> fix: use system default shell instead of /bin/sh

FlashSpace/Features/CLI/Commands/WorkspaceCommands.swift, FlashSpace/Features/CLI/Models/CommandRequest.swift, FlashSpace/Features/Gestures/SwipeManager.swift, FlashSpace/Features/Settings/Workspaces/WorkspaceSettings.swift, FlashSpace/Features/Settings/Workspaces/WorkspacesSettingsView.swift, FlashSpace/Features/Settings/_Models/AppSettings.swift, FlashSpace/Features/Workspaces/WorkspaceHotKeys.swift, FlashSpace/Features/Workspaces/WorkspaceManager.swift, FlashSpaceCLI/Sources/Models/CommandRequest.swift, FlashSpaceCLI/Sources/Subcommands/Workspace/WorkspaceCommand.swift, project.yml
=> feat(workspaces): added setting to skip empty workspaces

.github/workflows/pr.yml, FlashSpace/Features/PictureInPicture/PictureInPictureManager.swift, FlashSpace/Features/Settings/Workspaces/WorkspaceSettings.swift, FlashSpace/Features/Settings/Workspaces/WorkspacesSettingsView.swift, FlashSpace/Features/Settings/_Models/AppSettings.swift, project.yml
=> feat(pip): added screen corner offset setting

FlashSpace/App/AppConstants.swift, FlashSpace/Features/Profiles/Models/Profile.swift, FlashSpace/Features/Profiles/ProfilesRepository.swift, project.yml
Resolves #273
Now the setting is stored in UserDefaults:
`defaults read pl.wojciechkulik.FlashSpace selectedProfileId`
=> feat(profiles): removed selected profile id from config file

FlashSpace/Features/PictureInPicture/Extensions/AXUIElement+PiP.swift, FlashSpace/Features/PictureInPicture/Models/PipBrowser.swift, project.yml
=> fix(pip): Google Meet Picture-in-Picture in Chrome

FlashSpace/Features/MenuBar/FlashSpaceMenuBar.swift, FlashSpace/Features/Settings/MenuBar/MenuBarSettings.swift, FlashSpace/Features/Settings/MenuBar/MenuBarSettingsView.swift, FlashSpace/Features/Settings/_Models/AppSettings.swift, project.yml
=> feat(menu-bar): add option to hide menu bar icon

FlashSpace/Features/CLI/Commands/GetCommands.swift, FlashSpace/Features/CLI/Models/CommandRequest.swift, FlashSpaceCLI/Sources/Models/CommandRequest.swift, FlashSpaceCLI/Sources/Subcommands/Get/GetAppCommand.swift
=> feat(cli): add `--with-windows-count` flag for `get-app` command

FlashSpace/Accessibility/AXUIElement+CoreGraphics.swift, FlashSpace/Accessibility/AXUIElement+Properties.swift, FlashSpace/Accessibility/System.swift, FlashSpace/Extensions/MacAppArray.swift, FlashSpace/Extensions/URL.swift, FlashSpace/Features/FocusManager/Models/MacAppWithWindows.swift, FlashSpace/Features/PictureInPicture/Models/PipApp.swift, FlashSpace/Features/Workspaces/Models/MacApp.swift, FlashSpace/Features/Workspaces/WorkspaceManager.swift
=> feat(floating-apps): keep floating app focused when switching workspace

FlashSpace/Features/Settings/Workspaces/WorkspaceSettings.swift, FlashSpace/Features/Settings/Workspaces/WorkspacesSettingsView.swift, FlashSpace/Features/Settings/_Models/AppSettings.swift, FlashSpace/Features/Workspaces/WorkspaceManager.swift
=> feat(workspaces): add option `Keep unassigned apps on switch`

FlashSpace/Features/Workspaces/WorkspaceManager.swift
=> fix(floating-apps): incorrect focus behavior

FlashSpace/Features/CLI/Commands/AppCommands.swift, FlashSpace/Features/CLI/Commands/ListCommands.swift, FlashSpace/Features/CLI/Models/CommandRequest.swift, FlashSpaceCLI/Sources/FlashSpaceCLI.swift, FlashSpaceCLI/Sources/Models/CommandRequest.swift, FlashSpaceCLI/Sources/Subcommands/App/FloatingAppsCommand.swift, FlashSpaceCLI/Sources/Subcommands/List/ListFloatingAppsCommand.swift
=> feat(cli): add floating apps management

FlashSpace/Features/Settings/Workspaces/WorkspaceSettings.swift, FlashSpace/Features/Settings/Workspaces/WorkspacesSettingsView.swift, FlashSpace/Features/Settings/_Models/AppSettings.swift, FlashSpace/Features/Workspaces/WorkspaceManager.swift, project.yml
=> feat(workspaces): add option "Show Hidden Apps On Workspace Activation"

FlashSpace/Features/CLI/Commands/AppCommands.swift, FlashSpace/Features/CLI/Models/CommandRequest.swift, FlashSpace/Features/Settings/Workspaces/WorkspaceSettings.swift, FlashSpace/Features/Settings/Workspaces/WorkspacesSettingsView.swift, FlashSpace/Features/Settings/_Models/AppSettings.swift, FlashSpace/Features/Workspaces/WorkspaceHotKeys.swift, FlashSpace/Features/Workspaces/WorkspaceManager.swift, FlashSpaceCLI/Sources/FlashSpaceCLI.swift, FlashSpaceCLI/Sources/Models/CommandRequest.swift, FlashSpaceCLI/Sources/Subcommands/App/AssignVisibleAppsCommand.swift
=> feat(hotkeys): added hotkey to assign all visible apps

.gitignore, FlashSpace.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, FlashSpace/Features/MainScreen/MainView.swift, FlashSpace/Features/MainScreen/MainViewModel.swift, FlashSpace/Features/MenuBar/FlashSpaceMenuBar.swift, FlashSpace/Features/Settings/About/AboutSettingsView.swift, FlashSpace/Features/Settings/General/GeneralSettings.swift, FlashSpace/UI/Alerts.swift, FlashSpace/Utils/UpdatesManager.swift, fastlane/Fastfile, project.yml, sparkle/appcast.xml, sparkle/release-notes-template.html, sparkle/release-notes.html
=> feat: integrate auto-updater Sparkle

FlashSpace/Features/CLI/Commands/AppCommands.swift, FlashSpace/Features/CLI/Commands/WorkspaceCommands.swift, FlashSpace/Features/CLI/Models/CommandRequest.swift, FlashSpace/Features/Settings/Workspaces/WorkspaceSettings.swift, FlashSpace/Features/Settings/Workspaces/WorkspacesSettingsView.swift, FlashSpace/Features/Settings/_Models/AppSettings.swift, FlashSpace/Features/Workspaces/WorkspaceHotKeys.swift, FlashSpace/Features/Workspaces/WorkspaceManager.swift, FlashSpaceCLI/Sources/FlashSpaceCLI.swift, FlashSpaceCLI/Sources/Models/CommandRequest.swift, FlashSpaceCLI/Sources/Subcommands/App/HideUnassignedAppsCommand.swift, FlashSpaceCLI/Sources/Subcommands/Workspace/WorkspaceCommand.swift
=> feat(cli): add CLI command & hotkey to hide all unassigned apps

FlashSpace/App/AppDependencies.swift, FlashSpace/Extensions/View.swift, FlashSpace/Features/CLI/Commands/ListCommands.swift, FlashSpace/Features/MainScreen/MainViewModel.swift, FlashSpace/Features/MainScreen/WorkspaceConfigurationView.swift, FlashSpace/Features/Settings/Workspaces/DisplayMode.swift, FlashSpace/Features/Settings/Workspaces/WorkspaceSettings.swift, FlashSpace/Features/Settings/Workspaces/WorkspacesSettingsView.swift, FlashSpace/Features/Settings/_Models/AppSettings.swift, FlashSpace/Features/SpaceControl/WorkspaceScreenshotManager.swift, FlashSpace/Features/Workspaces/Models/Workspace.swift, FlashSpace/Features/Workspaces/WorkspaceHotKeys.swift
=> feat(workspaces): add global display mode setting

FlashSpace/Features/FocusManager/FocusedWindowTracker.swift, FlashSpace/Features/Workspaces/WorkspaceHotKeys.swift
=> fix(workspaces): activating workspace on app launch

FlashSpace/Features/SpaceControl/SpaceControl.swift
=> fix(space-control): block space control when less than 2 workspaces

FlashSpace/App/AppDependencies.swift, FlashSpace/Features/SpaceControl/Views/SpaceControlViewModel.swift, FlashSpace/Features/SpaceControl/WorkspaceScreenshotManager.swift
=> feat(space-control): support for dynamic mode

FlashSpace/Features/PictureInPicture/Models/PipBrowser.swift
=> feat(pip): add support for Dia

FlashSpace/Features/CLI/Commands/WorkspaceCommands.swift, FlashSpace/Features/CLI/Models/CommandRequest.swift, FlashSpace/Features/Gestures/SwipeManager.swift, FlashSpace/Features/Settings/Workspaces/WorkspaceSettings.swift, FlashSpace/Features/Settings/Workspaces/WorkspacesSettingsView.swift, FlashSpace/Features/Settings/_Models/AppSettings.swift, FlashSpace/Features/Workspaces/WorkspaceHotKeys.swift, FlashSpace/Features/Workspaces/WorkspaceManager.swift, FlashSpaceCLI/Sources/Models/CommandRequest.swift, FlashSpaceCLI/Sources/Subcommands/Workspace/WorkspaceCommand.swift
=> feat(workspaces): add "Loop Workspaces" option for next/prev workspace action

FlashSpace/Extensions/NotificationName.swift, FlashSpace/Features/PictureInPicture/PictureInPictureManager.swift, FlashSpace/Features/Settings/Workspaces/WorkspaceSettings.swift, FlashSpace/Features/Settings/Workspaces/WorkspacesSettingsView.swift, FlashSpace/Features/Settings/_Models/AppSettings.swift
=> feat(pip): add "Switch Workspace When PiP Closes" option

FlashSpace/Features/Gestures/SwipeManager.swift, FlashSpace/Features/Settings/Gestures/GesturesSettings.swift, FlashSpace/Features/Settings/Gestures/GesturesSettingsView.swift, FlashSpace/Features/Settings/_Models/AppSettings.swift
Resolves #253
See Gestures settings
=> feat(gestures): Add option to restart app on system wake up

README.md
@nbargnesi thank you very much for supporting the project 🍻 !
=> docs: update sponsors

FlashSpace/UI/Toast.swift
=> fix: show notifications above Dock

FlashSpace/Features/Integrations/Integrations.swift
=> feat(integrations): automatically find sketchybar's full path

FlashSpace/App/AppDelegate.swift
=> fix(gestures): show the app window only after first launch

FlashSpace/App/AppDependencies.swift, FlashSpace/Features/Workspaces/WorkspaceManager.swift
=> feat(profiles): remember last focused app per profile

FlashSpace/Features/Gestures/SwipeManager.swift
=> fix(gestures): restarting app on wake up

FlashSpace/Features/Workspaces/WorkspaceManager.swift
=> fix(workspaces): avoid endless loop on workspace switch

FlashSpace/Features/PictureInPicture/Models/PipGoogleMeet.swift
=> fix(pip): support for Google Meet PiP

.swiftformat, FlashSpace/Features/Integrations/Integrations.swift
=> feat(integrations): change "on workspace change" to work synchronously
